/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Signature = IDL.Record({
  'createdAt' : Time,
  'areaCode' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getSignatureCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSignatures' : IDL.Func([], [IDL.Vec(Signature)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Signature = IDL.Record({
    'createdAt' : Time,
    'areaCode' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'createSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getSignatureCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSignatures' : IDL.Func([], [IDL.Vec(Signature)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };